tag all .c files, clean bootstrap some

diff --git a/config/bootstrap b/config/bootstrap
--- a/config/bootstrap
+++ b/config/bootstrap
@@ -59,28 +59,23 @@ config_tools()
     if test -d "$TEMP_DIR"
     then
         TMPDIR="$TEMP_DIR"
-        i_made_temp_dir=false
-
-    elif shopt -qo xtrace
-    then
-        TMPDIR=${TMP:-/tmp}
-        i_made_temp_dir=false
+        must_remove_temp_dir=false
 
     else
-        TMPDIR=${TMP:-/tmp}/ag-bs-????????.tdir
+        TMPDIR=${TMPDIR:-/tmp}/ag-bs-????????.tdir
         rm -rf $TMPDIR
         TMPDIR=$(mktemp -d ${TMPDIR//\?/X})
-        : REDIRECT to  ${TMPDIR}/bs-log.txt
+        touch  ${TMPDIR}/bs-log.txt || \
+            die ${TMPDIR}/bs-log.txt is untouchable
         exec 2> ${TMPDIR}/bs-log.txt
-        i_made_temp_dir=true
-        trap "rm -rf ${TMPDIR}" 0
+        $VERBOSE && must_remove_temp_dir=false || must_remove_temp_dir=true
+        TEMP_DIR=$TMPDIR
     fi
-    export TMPDIR
+    export TMPDIR TEMP_DIR
 
-    config_file=configure.ac
     conf_dir=${top_srcdir}/config
-    test -f "${top_srcdir}/${config_file}.pre" || \
-        die "${config_file}.pre not in ${top_srcdir}"
+    test -f "${top_srcdir}/configure.ac.pre" || \
+        die "configure.ac.pre not in ${top_srcdir}"
 
     # ORDERED LIST. "pre" goes in this order, "post" in reverse so,
     # bootstrap.local pre is first and bootstrap.local post is last.
@@ -94,7 +89,7 @@ config_tools()
         getdefs/bootstrap.dir
         snprintfv/bootstrap.dir'
 
-    export config_file top_srcdir top_builddir bootstrap_list
+    export top_srcdir top_builddir bootstrap_list
     readonly bootstrap_list
 
     # ------------------------------------------------------------------
@@ -132,22 +127,20 @@ config_tools()
 # script, or afterwards.
 #
 source_bs() {
-    local file=${2}
-    cd ${file%/*}
-    file=${file##*/}
-    test -f $file && (
-        PS4="+${1#./}=\${FUNCNAME:-=}-\$LINENO> "
-        shift 2
-        : IN $PWD sourcing $file
-        source ${PWD}/${file} ${1+"$@"} || die ${file} failed
-    )
-    file=${PWD##*/}
-    cd - >/dev/null
+    local file=${1##*/}
+    local _PS4=${PWD##*/}
+    _PS4=+BS${_PS4:0:4}-$2='${FUNCNAME:-=}-$LINENO> '
+
+    test -f "$file" || die "cannot locate $file in $PWD"
+    : IN $PWD sourcing "$file"
+    PS4="$_PS4" source "$PWD/${file}" ${2} || \
+        die "$PWD/${file} failed"
 }
 
 sub_bootstrap()
 {
-    local list=
+    local list= start_dir=$PWD
+
     if test X$1 = Xpost
     then list=$(tac <<<"$bootstrap_list")
     else list="$bootstrap_list"
@@ -155,8 +148,11 @@ sub_bootstrap()
 
     for f in ${list}
     do
-        echo START $f ${1^^} $(date) > /dev/tty
-        source_bs ${f%/bootstrap.dir} $f $1
+        printf "START %-4s %-24s %s\n" $1 "$f" "$(date '+%M:%S.%N')" > /dev/tty
+        cd $(dirname "$f")
+        source_bs "$f" $1
+        cd "$start_dir"
+        printf "DONE  %-4s %-24s %s\n" $1 "$f" "$(date '+%M:%S.%N')" > /dev/tty
     done
 }
 
@@ -171,6 +167,34 @@ filter_chaff() {
     rm -f "${tool_out_file}"
 }
 
+fix_do_not_make_me() {
+    local fix_list=$(
+        grep -l FIX-DO-NOT-MAKE-ME \
+             $(find * -type f -name 'Makefile.am'))
+    local sedcmd= vlist= f= v=
+
+    for f in $fix_list
+    do
+        sedcmd=$'/##FIX-DO-NOT-MAKE-ME/ {\ns/.*//\n'
+        vlist=$(sed -n '/do_not_make_me/s/ *[+=].*//p' $f | \
+                    sort -u)
+        if test ${#vlist} -gt 1
+        then
+            sedcmd+=$'i\\\n'
+            for v in $vlist
+            do
+                sedcmd+="$(printf '%-32s=' $v)"
+                sedcmd+=$'\\\n'
+            done
+            sedcmd+=$'\n'
+        fi
+        sedcmd+='}'
+
+        sed "$sedcmd" $f > $f.XX
+        mv -f $f.XX $f
+    done
+}
+
 run_autotools()
 {
     cd ${top_builddir}
@@ -180,6 +204,8 @@ run_autotools()
 
     test -n "$auxdir" || auxdir=${top_srcdir}
     test -d $auxdir   || auxdir=.
+
+    fix_do_not_make_me
 
     doit $LIBTOOLIZE    --force
     doit $ACLOCAL       -I config
@@ -203,14 +229,14 @@ run_autotools()
 {
     config_tools
     sub_bootstrap pre
-    tool_out_file=${TMPDIR}/autotool-out.txt
+    tool_out_file=${TEMP_DIR:-${TMPDIR:-/tmp}}/autotool-out.txt
     run_autotools 1> ${tool_out_file} 2>&1
     filter_chaff ${tool_out_file}
     sub_bootstrap post
 
     trap '' 0
     echo 'bootstrap complete' $(date)
-    ${i_made_temp_dir} && rm -rf ${TMPDIR}
+    ${must_remove_temp_dir} && rm_temp_dir
     : ; exit 0
 }
 # Local Variables:
